# Generated by Django 3.0.5 on 2020-04-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='spciy',
            new_name='spicy',
        ),
    ]
