# Generated by Django 3.0.5 on 2020-04-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0002_auto_20200410_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spicylevel',
            old_name='spice_name',
            new_name='spicy_name',
        ),
    ]
